### ISSUE TITLE
How do I create a 'normal' line chart in WPF with this?

### ISSUE THREAD

**Issue by wja-devries** [varon/GLGraph#1]
Very interested to hear this is 'way faster than LiveCharts', and the scatter- and network chart examples are impressive.
But how do I create a normal line chart with multiple series/axis and a white background?
A little more examples would be great!
Is anyone willing to spend the time to give me some examples?

**Comment by varon** [comment]
use the `SeriesType.Line` instead of `SeriesType.point`
